export type KnowledgeBlock =
  | { type: "lead"; text: string }
  | { type: "paragraph"; text: string }
  | { type: "heading"; text: string }
  | { type: "callout"; label?: string; text: string }
  | { type: "formula"; lines: string[] }
  | { type: "list"; items: string[] };

export type KnowledgeArticle = {
  number: number;
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  track?: "entrepreneur" | "controlling-ai";
  readTime: string;
  blocks: KnowledgeBlock[];
};

export const knowledgeArticles: KnowledgeArticle[] = [
  {
    number: 1,
    slug: "zysk-to-nie-gotowka",
    title: "Zysk to nie gotówka. Dlaczego firma może zarabiać i jednocześnie nie mieć pieniędzy?",
    excerpt: "Najważniejsza różnica w finansach małej firmy: wynik mówi, czy biznes zarabia, a gotówka — czy ma czym płacić.",
    category: "Fundamenty finansów",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "To jedna z najważniejszych rzeczy do zrozumienia w finansach firmy: zysk i gotówka to nie to samo." },
      { type: "paragraph", text: "Wyobraź sobie firmę, która w marcu sprzedała usługi za 100 tys. zł. Koszt ich wykonania wyniósł 70 tys. zł. Na papierze firma zarobiła więc 30 tys. zł." },
      { type: "paragraph", text: "Problem w tym, że klienci mają 45 dni na zapłatę. W marcu firma wystawiła faktury, ale pieniędzy jeszcze nie dostała. Jednocześnie musiała zapłacić pracownikom, dostawcom, ZUS i czynsz." },
      { type: "callout", label: "Wniosek", text: "Firma może mieć 30 tys. zł zysku i jednocześnie ubytek pieniędzy na rachunku." },
      { type: "paragraph", text: "Działa to również w drugą stronę. Jeśli firma zaciągnie kredyt na 100 tys. zł, jej konto zwiększy się o 100 tys. zł, ale nie oznacza to, że cokolwiek zarobiła." },
      { type: "paragraph", text: "Podobnie zakup samochodu za 120 tys. zł może spowodować jednorazowy duży wypływ pieniędzy, podczas gdy w wyniku finansowym koszt będzie rozłożony na kilka lat poprzez amortyzację." },
      { type: "heading", text: "Na jakie dwa pytania patrzeć równocześnie?" },
      { type: "list", items: ["Czy moja działalność jest rentowna?", "Czy generuje wystarczająco dużo gotówki?"] },
      { type: "paragraph", text: "Firma może być rentowna, ale mieć problemy z płynnością. Może też przez pewien czas mieć dużo pieniędzy na koncie, mimo że jej podstawowy biznes przynosi straty." },
      { type: "callout", text: "Nie pytaj tylko: „Ile zarobiłem?”. Dodaj drugie pytanie: „Dlaczego mam dziś więcej lub mniej pieniędzy niż miesiąc temu?”" },
      { type: "paragraph", text: "Dopiero odpowiedź na oba pytania daje prawdziwy obraz sytuacji." }
    ]
  },
  {
    number: 2,
    slug: "ile-naprawde-zarabia-firma",
    title: "Ile naprawdę zarabia moja firma?",
    excerpt: "Obrót to nie wynik. Zobacz, jak przejść od sprzedaży do ekonomicznego obrazu tego, ile naprawdę zostaje właścicielowi.",
    category: "Fundamenty finansów",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Przedsiębiorcy często odpowiadają na pytanie o wyniki firmy, podając sprzedaż: „Robimy około 150 tysięcy miesięcznie”. To ważna informacja, ale nie mówi jeszcze, ile firma rzeczywiście zarabia." },
      { type: "paragraph", text: "Załóżmy, że firma sprzedaje miesięcznie za 150 tys. zł netto. Materiały i towary kosztują 60 tys. zł. Wynagrodzenia 35 tys. zł. Czynsz, samochody, księgowość, telefony, systemy IT i inne koszty to kolejne 30 tys. zł." },
      { type: "formula", lines: ["150 tys. zł sprzedaży", "− 60 tys. zł materiały i towary", "− 35 tys. zł wynagrodzenia", "− 30 tys. zł pozostałe koszty", "= 25 tys. zł wyniku"] },
      { type: "paragraph", text: "To pierwszy obraz wyniku. Ale nawet wtedy warto zadać kolejne pytania: czy właściciel pracuje w firmie, ile godzin, czy pobiera normalne wynagrodzenie i czy w danym miesiącu nie pojawiły się koszty wyjątkowo niskie albo wysokie." },
      { type: "paragraph", text: "Wyobraźmy sobie przedsiębiorcę, który pracuje 200 godzin miesięcznie, ale nie wypłaca sobie wynagrodzenia. Gdyby zatrudnienie osoby wykonującej podobną pracę kosztowało firmę 15 tys. zł miesięcznie, ekonomiczny wynik biznesu nie wynosi już 25 tys. zł, ale raczej około 10 tys. zł." },
      { type: "heading", text: "Dwa różne wyniki" },
      { type: "list", items: ["Wynik księgowy — wynikający z zasad rachunkowych lub podatkowych.", "Wynik ekonomiczny — odpowiadający na pytanie, ile biznes naprawdę zarabia po uwzględnieniu wszystkich zasobów potrzebnych do jego funkcjonowania."] },
      { type: "paragraph", text: "W małej firmie drugi z tych wyników jest często znacznie ważniejszy dla właściciela." },
      { type: "callout", text: "Jeśli przedsiębiorca pracuje po 10 godzin dziennie, a po uwzględnieniu wartości własnej pracy biznes generuje 3 tys. zł zysku, problemem może być nie księgowość, lecz model biznesowy." }
    ]
  },
  {
    number: 3,
    slug: "wlasciciel-pracuje-za-darmo",
    title: "Pracuję we własnej firmie za darmo. Czy mój zysk jest prawdziwy?",
    excerpt: "Darmowa praca właściciela i rodziny może mocno zawyżać obraz rentowności. Jak policzyć wynik ekonomiczny firmy?",
    category: "Fundamenty finansów",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "W wielu mikrofirmach właściciel nie pobiera normalnego wynagrodzenia. Podobnie bywa z małżonkiem, rodzicami czy dziećmi pomagającymi w działalności. Księgowo firma może wyglądać wtedy bardzo dobrze." },
      { type: "paragraph", text: "Przykład: firma osiąga miesięcznie 100 tys. zł sprzedaży, 80 tys. zł kosztów i 20 tys. zł wyniku. Wygląda nieźle." },
      { type: "paragraph", text: "Ale właściciel pracuje w niej codziennie po 9 godzin. Jego żona zajmuje się administracją i rozliczeniami po kilka godzin dziennie. Żadne z nich nie pobiera rynkowego wynagrodzenia." },
      { type: "paragraph", text: "Gdyby firma musiała zatrudnić menedżera za 12 tys. zł oraz osobę administracyjną za 5 tys. zł, ekonomiczny wynik spadłby z 20 tys. do około 3 tys. zł." },
      { type: "callout", label: "Co naprawdę widzimy?", text: "Większa część „zysku” jest w rzeczywistości wynagrodzeniem właścicieli za ich pracę." },
      { type: "paragraph", text: "Nie ma w tym nic złego. Problem powstaje dopiero wtedy, kiedy przedsiębiorca uważa całe 20 tys. zł za zwrot z posiadania firmy." },
      { type: "callout", text: "Dobry test: „Co stałoby się z wynikiem, gdybym jutro musiał zatrudnić kogoś na swoje miejsce?”" },
      { type: "paragraph", text: "Jeżeli po uwzględnieniu takiego kosztu firma nadal zarabia — mamy biznes zdolny generować zysk niezależnie od darmowej pracy właściciela." },
      { type: "paragraph", text: "Jeżeli wynik spada do zera, firma może być przede wszystkim dobrze płatnym miejscem pracy dla właściciela, a nie samodzielnie zarabiającym aktywem." },
      { type: "paragraph", text: "To bardzo istotne przy podejmowaniu decyzji o rozwoju, zatrudnianiu ludzi, sprzedaży firmy czy ocenie, czy warto dalej skalować działalność." }
    ]
  },
  {
    number: 4,
    slug: "zysk-jdg-a-spolka-zoo",
    title: "Zysk w JDG i zysk w spółce z o.o. to nie do końca to samo",
    excerpt: "Wypłata właściciela, wynik firmy i podatek to trzy różne rzeczy. Szczególnie wyraźnie widać to przy porównaniu JDG i spółki.",
    category: "Fundamenty finansów",
    readTime: "5 min",
    blocks: [
      { type: "lead", text: "W jednoosobowej działalności gospodarczej właściciel i biznes są ze sobą znacznie mocniej połączeni niż w spółce kapitałowej. To powoduje wiele nieporozumień." },
      { type: "paragraph", text: "W JDG przedsiębiorca może np. przelać pieniądze z rachunku firmowego na prywatny. Taki przelew sam w sobie nie jest wynagrodzeniem ani kosztem firmy." },
      { type: "paragraph", text: "Jeżeli firma wypracowała 20 tys. zł dochodu, a właściciel wypłacił sobie 15 tys. zł na prywatne konto, nie oznacza to, że firma osiągnęła 5 tys. zł zysku. Wypłata właściciela jest czymś innym niż koszt prowadzenia działalności." },
      { type: "paragraph", text: "W spółce z o.o. sytuacja wygląda inaczej. Spółka jest odrębnym podmiotem. Pieniądze znajdujące się na jej rachunku nie są automatycznie prywatnymi pieniędzmi wspólnika." },
      { type: "paragraph", text: "Właściciel może otrzymywać pieniądze ze spółki na określonych zasadach, np. jako wynagrodzenie, zwrot określonych kosztów czy dywidendę." },
      { type: "heading", text: "Wynik biznesowy a wynik podatkowy" },
      { type: "paragraph", text: "Wynik biznesowy i wynik podatkowy również nie zawsze są tym samym. W JDG sposób liczenia podatku zależy m.in. od wybranej formy opodatkowania. Przedsiębiorca na ryczałcie może płacić podatek od przychodu, mimo że z ekonomicznego punktu widzenia nadal powinien wiedzieć, ile jego biznes faktycznie zarabia po kosztach." },
      { type: "formula", lines: ["przychody", "− rzeczywiste koszty działalności", "− ekonomiczny koszt pracy właściciela", "= wynik biznesu"] },
      { type: "callout", text: "Forma prawna i podatki wpływają na to, jak pieniądze są rozliczane. Podstawowe pytanie pozostaje jednak takie samo: czy biznes po uwzględnieniu wszystkich potrzebnych zasobów naprawdę tworzy wartość?" }
    ]
  },
  {
    number: 5,
    slug: "plynnosc-finansowa",
    title: "Płynność finansowa: firma upada nie wtedy, gdy nie ma zysku, ale gdy nie ma czym zapłacić",
    excerpt: "Płynność to nie saldo dzisiaj. To odpowiedź na pytanie, czy firma będzie miała pieniądze wtedy, kiedy pojawią się zobowiązania.",
    category: "Płynność i gotówka",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Można prowadzić firmę, która zarabia, i jednocześnie nie mieć pieniędzy na wypłatę wynagrodzeń. To właśnie problem płynności." },
      { type: "callout", label: "Najprościej", text: "Płynność oznacza: czy będę miał pieniądze wtedy, kiedy trzeba będzie coś zapłacić?" },
      { type: "paragraph", text: "Nie chodzi tylko o dzisiejsze saldo bankowe. Załóżmy, że firma ma dziś 80 tys. zł na rachunku. Wygląda bezpiecznie." },
      { type: "paragraph", text: "Ale w ciągu najbliższych dwóch tygodni musi zapłacić 30 tys. zł wynagrodzeń, 18 tys. zł VAT i innych podatków, 25 tys. zł dostawcom i 10 tys. zł rat kredytów. Łącznie 83 tys. zł." },
      { type: "paragraph", text: "Jeżeli w tym czasie spodziewane wpływy wynoszą tylko 20 tys. zł, firma ma problem, mimo że dzisiejsze saldo wygląda komfortowo." },
      { type: "heading", text: "Płynnością zarządza się do przodu" },
      { type: "formula", lines: ["saldo początkowe", "+ oczekiwane wpływy", "− przewidywane wydatki", "= prognozowane saldo"] },
      { type: "paragraph", text: "Prognoza nie musi być idealnie dokładna. Ma ostrzegać. Jeśli dzisiaj widzisz, że za pięć tygodni zabraknie 30 tys. zł, masz czas: możesz przyspieszyć ściąganie należności, przesunąć inwestycję, porozmawiać z dostawcą albo bankiem." },
      { type: "callout", text: "Płynność to nie księgowość. To system wczesnego ostrzegania firmy." }
    ]
  },
  {
    number: 6,
    slug: "saldo-na-koncie",
    title: "Saldo na koncie nie mówi, ile pieniędzy naprawdę masz",
    excerpt: "Na rachunku może leżeć 120 tys. zł, ale część tej kwoty może już być ekonomicznie zarezerwowana na podatki, ludzi i dostawców.",
    category: "Płynność i gotówka",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Na rachunku firmowym jest 120 tys. zł. Czy możesz wydać 100 tys. na nową maszynę? Niekoniecznie." },
      { type: "paragraph", text: "Część pieniędzy znajdujących się na rachunku może być już ekonomicznie „zarezerwowana”. Przykładowo w ciągu najbliższych tygodni firma musi zapłacić 25 tys. zł VAT, 15 tys. zł innych podatków i składek, 30 tys. zł wynagrodzeń i 20 tys. zł dostawcom." },
      { type: "formula", lines: ["120 tys. zł na rachunku", "− 25 tys. zł VAT", "− 15 tys. zł podatki i składki", "− 30 tys. zł wynagrodzenia", "− 20 tys. zł dostawcy", "≈ 30 tys. zł względnie wolnej gotówki"] },
      { type: "paragraph", text: "To oczywiście uproszczenie, bo w międzyczasie pojawią się kolejne wpływy i wydatki. Pokazuje jednak ważną zasadę: saldo bankowe nie jest tym samym co pieniądze dostępne do swobodnego wykorzystania." },
      { type: "heading", text: "Trzy mentalne koszyki" },
      { type: "list", items: ["Pieniądze potrzebne do normalnego działania firmy.", "Zobowiązania, które wkrótce trzeba będzie zapłacić.", "Środki, które można uznać za względnie wolne."] },
      { type: "paragraph", text: "To szczególnie ważne w firmach, które otrzymują duże zaliczki od klientów albo mają silną sezonowość. Hotel może mieć w maju dużo pieniędzy z rezerwacji wakacyjnych, ale część tej gotówki będzie potrzebna do obsługi klientów w lipcu i sierpniu." },
      { type: "callout", text: "Duże saldo daje poczucie bezpieczeństwa. Czasami fałszywe. Lepsze pytanie brzmi: ile pieniędzy pozostanie mi po uwzględnieniu zobowiązań najbliższych tygodni?" }
    ]
  },
  {
    number: 7,
    slug: "ile-gotowki-wygenerowala-firma",
    title: "Ile gotówki firma wygenerowała w tym miesiącu?",
    excerpt: "Wzrost salda nie zawsze oznacza, że biznes wygenerował gotówkę. Kredyt, inwestycja albo wypłata właściciela mogą całkowicie zmienić obraz.",
    category: "Płynność i gotówka",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Najprostszy punkt wyjścia to porównanie rachunku bankowego. Na początku miesiąca firma miała 70 tys. zł, a na końcu 95 tys. zł. Gotówki przybyło więc 25 tys. zł." },
      { type: "paragraph", text: "Czy firma wygenerowała 25 tys. zł z podstawowej działalności? Nie wiemy." },
      { type: "paragraph", text: "Być może właściciel wpłacił do firmy 50 tys. zł pożyczki. Wtedy działalność operacyjna mogła faktycznie zużyć 25 tys. zł. Albo firma kupiła za gotówkę samochód za 60 tys. zł. Wtedy podstawowa działalność mogła wygenerować aż 85 tys. zł, z których 60 tys. zostało przeznaczone na inwestycję." },
      { type: "heading", text: "Rozłóż zmianę gotówki na przyczyny" },
      { type: "list", items: ["Działalność operacyjna — pieniądze od klientów minus codzienne wydatki.", "Inwestycje — samochody, maszyny, wyposażenie.", "Finansowanie — kredyty, pożyczki i ich spłaty.", "Wypłaty właścicielskie."] },
      { type: "callout", text: "Zamiast: „Saldo wzrosło o 25 tys.” lepiej wiedzieć: „Biznes wygenerował 70 tys., 30 tys. przeznaczyliśmy na inwestycje, 15 tys. na spłatę kredytu. Zostało 25 tys.”" },
      { type: "paragraph", text: "Nie chodzi o budowanie profesjonalnego rachunku przepływów pieniężnych. Chodzi o zrozumienie skąd naprawdę biorą się pieniądze i gdzie znikają." }
    ]
  },
  {
    number: 8,
    slug: "wzrost-sprzedazy-a-gotowka",
    title: "Dlaczego rosnąca sprzedaż może doprowadzić firmę do problemów z gotówką?",
    excerpt: "Szybki wzrost może wymagać coraz większego finansowania zapasów, ludzi i należności, zanim klient zapłaci.",
    category: "Płynność i gotówka",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Więcej sprzedaży brzmi jak dobra wiadomość. I zwykle nią jest. Ale szybki wzrost potrafi również doprowadzić firmę do kryzysu płynności." },
      { type: "paragraph", text: "Załóżmy, że firma otrzymuje duże zamówienie. Aby je zrealizować, musi kupić za 80 tys. zł materiałów, zapłacić pracownikom i transportowi. Klient zapłaci dopiero 60 dni po wystawieniu faktury." },
      { type: "paragraph", text: "Firma zarobi na kontrakcie 30 tys. zł, ale zanim otrzyma pieniądze, musi sfinansować całe przedsięwzięcie z własnej kieszeni. Jeżeli takich zamówień pojawi się kilka naraz, może zabraknąć gotówki." },
      { type: "callout", label: "Paradoks wzrostu", text: "Im szybciej rośnie firma, tym więcej pieniędzy może potrzebować." },
      { type: "paragraph", text: "Szczególnie dotyczy to firm, które utrzymują zapasy, dają klientom długie terminy płatności, muszą płacić dostawcom szybko albo zatrudniają ludzi przed pojawieniem się dodatkowej sprzedaży." },
      { type: "heading", text: "Przed dużym kontraktem zadaj dwa pytania" },
      { type: "list", items: ["Ile na nim zarobię?", "Ile pieniędzy muszę wyłożyć i na jak długo?"] },
      { type: "paragraph", text: "Duże zamówienie, które daje 15% marży, ale wymaga zamrożenia kilkuset tysięcy złotych na trzy miesiące, może być dla niewielkiej firmy znacznie trudniejsze niż mniejszy kontrakt płatny z góry." },
      { type: "callout", text: "Wzrost powinien być nie tylko rentowny. Powinien być również finansowalny." }
    ]
  },
  {
    number: 9,
    slug: "naleznosci-sprzedaz-to-nie-pieniadze",
    title: "Należności: sprzedaż to jeszcze nie pieniądze",
    excerpt: "Faktura zwiększa sprzedaż, ale dopiero zapłata zwiększa gotówkę. Jak nie zostać bankiem swoich klientów?",
    category: "Płynność i gotówka",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Wystawienie faktury nie oznacza, że firma otrzymała pieniądze. Do momentu zapłaty mamy należność." },
      { type: "paragraph", text: "Załóżmy, że w maju firma sprzedała towary za 200 tys. zł. Na rachunek wpłynęło tylko 140 tys. zł. Pozostałe 60 tys. czeka na zapłatę. Firma wykonała swoją część pracy, ale nadal finansuje klienta." },
      { type: "paragraph", text: "Jeżeli termin płatności wynosi 30 dni, jest to normalny element biznesu. Problem zaczyna się wtedy, gdy 30 dni zmienia się w 60, 90 albo 120." },
      { type: "paragraph", text: "Przy dużej liczbie klientów trudno zauważyć pogorszenie sytuacji. Sprzedaż może nawet rosnąć, a jednocześnie coraz większa jej część pozostaje niezapłacona." },
      { type: "heading", text: "Nie patrz tylko na sumę należności" },
      { type: "paragraph", text: "Warto obserwować również ich wiek. Inaczej należy patrzeć na fakturę wystawioną pięć dni temu, a inaczej na fakturę, która jest 70 dni po terminie." },
      { type: "paragraph", text: "Dobre zarządzanie należnościami zaczyna się przed wystawieniem faktury: komu sprzedajemy, jaki dajemy termin, czy klient zawsze płaci terminowo i czy przy większym zamówieniu nie warto pobrać zaliczki." },
      { type: "callout", text: "Każda złotówka, której klient jeszcze nie zapłacił, musi zostać chwilowo sfinansowana przez kogoś innego. Najczęściej przez przedsiębiorcę." }
    ]
  },
  {
    number: 10,
    slug: "kapital-obrotowy",
    title: "Kapitał obrotowy bez podręcznikowych definicji",
    excerpt: "Kapitał obrotowy to w praktyce pieniądze zamrożone między zakupem, magazynem, sprzedażą i zapłatą klienta.",
    category: "Płynność i gotówka",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Kapitał obrotowy brzmi jak termin dla księgowych. W praktyce chodzi o bardzo prostą rzecz: ile pieniędzy firma musi zamrozić, zanim klient jej zapłaci." },
      { type: "paragraph", text: "Wyobraźmy sobie sklep. Kupuje towar za 50 tys. zł. Towar leży przez miesiąc na magazynie. Potem zostaje sprzedany klientowi, który płaci po kolejnych 30 dniach." },
      { type: "paragraph", text: "Od momentu zakupu towaru do otrzymania pieniędzy mijają dwa miesiące. Przez ten czas firma musi finansować te 50 tys. zł." },
      { type: "paragraph", text: "Jeśli dostawca da jej 30 dni terminu płatności, sytuacja się poprawia. Przez pierwszy miesiąc część finansowania zapewnia dostawca." },
      { type: "heading", text: "Trzy elementy, które warto śledzić" },
      { type: "list", items: ["Zapasy.", "Należności od klientów.", "Zobowiązania wobec dostawców."] },
      { type: "paragraph", text: "Im więcej pieniędzy jest zamrożonych w zapasach i niezapłaconych fakturach, tym większe finansowanie jest potrzebne." },
      { type: "paragraph", text: "Dlatego poprawa sytuacji finansowej nie zawsze wymaga zwiększenia sprzedaży. Czasem wystarczy szybciej sprzedawać zapasy, skrócić klientom terminy płatności, skuteczniej windykować należności albo wynegocjować lepsze terminy z dostawcami." },
      { type: "callout", text: "Dobre zarządzanie kapitałem obrotowym potrafi uwolnić gotówkę bez zdobycia choćby jednego dodatkowego klienta." }
    ]
  },
  {
    number: 11,
    slug: "obrot-rosnie-czy-zysk-tez",
    title: "Obrót rośnie. A czy firma naprawdę zarabia więcej?",
    excerpt: "Wzrost sprzedaży może oznaczać więcej pracy, większe ryzyko i… mniejszy zysk. Dlatego sam obrót to za mało.",
    category: "Rentowność i sprzedaż",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Firma sprzedała w zeszłym roku za 2 mln zł. W tym roku za 2,6 mln. Wzrost o 30%. Świetnie? Być może." },
      { type: "paragraph", text: "Załóżmy jednak, że przy sprzedaży 2 mln firma zarabiała 200 tys. zł, a przy sprzedaży 2,6 mln tylko 120 tys. Przedsiębiorca ma więcej klientów, więcej faktur, więcej pracowników i więcej problemów. A mniej zysku." },
      { type: "paragraph", text: "Sprzedaż można zwiększać poprzez rabaty, droższą reklamę, wejście do mniej rentownych segmentów albo obsługę klientów wymagających dużo dodatkowej pracy." },
      { type: "callout", text: "Dlatego wzrost sprzedaży zawsze warto zestawić przynajmniej z marżą albo zyskiem." },
      { type: "paragraph", text: "Jeśli sprzedaż rośnie o 30%, ale koszty rosną o 40%, wzrost może niszczyć wartość." },
      { type: "paragraph", text: "Jeszcze bardziej mylące są rekordowe miesiące. „Pierwszy raz przekroczyliśmy 300 tys. sprzedaży!” to sukces sprzedażowy. Z punktu widzenia właściciela ważniejsze pytanie brzmi jednak: ile z tych dodatkowych 100 tys. zł zostało w firmie?" },
      { type: "callout", label: "Zasada", text: "Liczy się wartościowa sprzedaż, a nie każda sprzedaż." }
    ]
  },
  {
    number: 12,
    slug: "marza-narzut-rentownosc",
    title: "Marża, narzut i rentowność — trzy pojęcia, które często są mylone",
    excerpt: "Kupujesz za 70 zł, sprzedajesz za 100 zł. Marża wynosi 30%, ale narzut już 42,9%. Skąd bierze się różnica?",
    category: "Rentowność i sprzedaż",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Kupujesz produkt za 70 zł. Sprzedajesz za 100 zł. Zarabiasz 30 zł. Jaka jest marża? 30%. A jaki jest narzut? Około 42,9%." },
      { type: "formula", lines: ["Marża = 30 zł / 100 zł = 30%", "Narzut = 30 zł / 70 zł ≈ 42,9%"] },
      { type: "paragraph", text: "To częste źródło błędów. Jeżeli przedsiębiorca mówi „dodaję 30% marży”, ale w praktyce mnoży koszt 70 zł przez 1,30, uzyska cenę 91 zł. Jego rzeczywista marża wyniesie wtedy tylko około 23%." },
      { type: "heading", text: "Co mierzą te pojęcia?" },
      { type: "list", items: ["Marża: jaka część sprzedaży zostaje po określonych kosztach?", "Narzut: o ile podniosłem cenę w stosunku do kosztu?", "Rentowność: szersza ocena opłacalności firmy, klienta, produktu czy inwestycji."] },
      { type: "paragraph", text: "W zarządzaniu warto używać przede wszystkim marży, ponieważ łatwo porównuje różne produkty i okresy. Trzeba jednak ustalić, jaką marżę liczymy." },
      { type: "paragraph", text: "Jeśli od ceny odejmujemy tylko zakup towaru, otrzymujemy jedną informację. Jeżeli odejmiemy również transport, prowizję handlowca i koszt obsługi — inną." },
      { type: "callout", text: "Dwie osoby mogą mówić o „marży 30%” i mieć na myśli zupełnie różne rzeczy. Zawsze ustal, jakie koszty uwzględniasz." }
    ]
  },
  {
    number: 13,
    slug: "rentownosc-klienta",
    title: "Który klient naprawdę na mnie zarabia?",
    excerpt: "Największy klient nie zawsze jest najlepszy. Rabaty, obsługa, reklamacje i termin płatności mogą zjadać pozornie atrakcyjną sprzedaż.",
    category: "Rentowność i sprzedaż",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Największy klient nie zawsze jest najlepszym klientem." },
      { type: "paragraph", text: "Wyobraźmy sobie dwóch kontrahentów. Klient A kupuje za 500 tys. zł rocznie, klient B za 250 tys. Na pierwszy rzut oka A jest dwa razy ważniejszy." },
      { type: "paragraph", text: "Ale A negocjuje duże rabaty, wymaga indywidualnych dostaw, regularnie składa reklamacje, angażuje handlowca i płaci po 75 dniach. Klient B kupuje standardową ofertę, prawie nie generuje dodatkowej obsługi i płaci po siedmiu dniach." },
      { type: "callout", text: "Po policzeniu wszystkich kosztów może się okazać, że mniejszy klient przynosi więcej zysku." },
      { type: "heading", text: "Co warto doliczyć do kosztu klienta?" },
      { type: "list", items: ["transport", "rabaty", "czas pracowników", "reklamacje", "niestandardowe zamówienia", "finansowanie długiego terminu płatności"] },
      { type: "paragraph", text: "Nie wszystko trzeba liczyć co do złotówki. Czasami wystarczy rozsądne przybliżenie." },
      { type: "paragraph", text: "Klient generujący 15% sprzedaży może wyglądać strategicznie, ale jeśli po uwzględnieniu obsługi daje 2% zysku, warto wiedzieć o tym przed kolejnymi negocjacjami." },
      { type: "callout", text: "Nie chodzi o natychmiastowe rezygnowanie z trudnych klientów. Chodzi o wiedzę, dzięki której można zmienić cenę, warunki dostawy, zakres obsługi albo termin płatności." }
    ]
  },
  {
    number: 14,
    slug: "rentownosc-produktu-uslugi",
    title: "Który produkt lub usługa naprawdę zarabia?",
    excerpt: "Duża sprzedaż nie gwarantuje wysokiej rentowności. Czasem najbardziej popularna usługa najbardziej obciąża firmę.",
    category: "Rentowność i sprzedaż",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Firma może być rentowna jako całość i jednocześnie tracić pieniądze na części swojej oferty. Problem polega na tym, że nierentowny produkt potrafi długo ukrywać się za dobrymi wynikami innych produktów." },
      { type: "paragraph", text: "Załóżmy, że firma sprzedaje dwa rodzaje usług. Usługa A kosztuje klienta 10 tys. zł i wymaga około 40 godzin pracy. Usługa B kosztuje 15 tys. zł, ale wymaga 120 godzin pracy, licznych poprawek i zaangażowania właściciela." },
      { type: "paragraph", text: "B daje większą sprzedaż. Ale może dawać mniejszy zysk." },
      { type: "callout", text: "Pierwsze pytanie: jakie koszty powstają dlatego, że wykonujemy tę konkretną usługę?" },
      { type: "list", items: ["materiały", "czas pracowników", "prowizje", "podwykonawcy", "transport"] },
      { type: "paragraph", text: "To daje pierwszą marżę. Następnie warto zastanowić się, ile produkt zużywa innych zasobów: administracji, powierzchni, czasu właściciela czy kapitału." },
      { type: "paragraph", text: "Nie chodzi o budowanie skomplikowanego systemu kalkulacji. W mikrofirmie często wystarczy podzielić ofertę na kilka grup i sprawdzić, gdzie naprawdę powstaje wynik." },
      { type: "paragraph", text: "Taka analiza może prowadzić do prostych decyzji: podnieść cenę, uprościć usługę, wycofać nierentowny wariant albo skierować sprzedaż na bardziej opłacalne produkty." },
      { type: "callout", text: "Czasami najlepszym sposobem na zwiększenie zysku firmy jest sprzedawać mniej tego, czego sprzedajemy dużo." }
    ]
  },
  {
    number: 15,
    slug: "koszty-stale-i-zmienne",
    title: "Koszty stałe i zmienne — po co przedsiębiorcy ta wiedza?",
    excerpt: "To rozróżnienie pokazuje, dlaczego spadek sprzedaży o 20% może obniżyć zysk nawet o 80%.",
    category: "Rentowność i sprzedaż",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Nie wszystkie koszty zachowują się tak samo. Czynsz za lokal zwykle nie zmieni się dlatego, że sprzedasz o jeden produkt więcej. Koszt materiału potrzebnego do tego produktu — tak." },
      { type: "paragraph", text: "Pierwszy koszt jest w dużej mierze stały. Drugi — zmienny. Po co to rozróżnienie? Bo pomaga przewidzieć, co stanie się z firmą, kiedy sprzedaż wzrośnie albo spadnie." },
      { type: "paragraph", text: "Załóżmy, że firma sprzedaje miesięcznie za 100 tys. zł. Koszty zmienne wynoszą 60 tys., a stałe 30 tys. Zysk to 10 tys." },
      { type: "formula", lines: ["100 tys. zł sprzedaży", "− 60 tys. zł kosztów zmiennych", "− 30 tys. zł kosztów stałych", "= 10 tys. zł zysku"] },
      { type: "paragraph", text: "Jeżeli sprzedaż spadnie o 20%, do 80 tys., koszty zmienne mogą spaść do około 48 tys. Koszty stałe nadal wyniosą jednak 30 tys. Zysk spadnie z 10 tys. do zaledwie 2 tys." },
      { type: "callout", text: "Sprzedaż zmniejszyła się o 20%. Zysk aż o 80%." },
      { type: "paragraph", text: "To pokazuje, dlaczego firmy z wysokimi kosztami stałymi są wrażliwe na spadki sprzedaży. Mechanizm działa również w drugą stronę: jeżeli firma ma już ludzi, lokal i maszyny, dodatkowa sprzedaż może dawać bardzo wysoką marżę." },
      { type: "paragraph", text: "Znajomość struktury kosztów pomaga podejmować decyzje dotyczące cen, zatrudnienia, inwestycji i ryzyka." }
    ]
  },
  {
    number: 16,
    slug: "prog-rentownosci",
    title: "Próg rentowności: ile muszę sprzedać, żeby wyjść na zero?",
    excerpt: "Jedna z najbardziej użytecznych liczb w małej firmie: poziom sprzedaży, od którego biznes zaczyna zarabiać.",
    category: "Rentowność i sprzedaż",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Załóżmy, że Twoja firma ma 30 tys. zł kosztów stałych miesięcznie. Na każdej sprzedaży za 100 zł po pokryciu kosztów bezpośrednich zostaje Ci 40 zł." },
      { type: "paragraph", text: "Te 40 zł musi najpierw pokryć koszty stałe. Dopiero potem zaczyna powstawać zysk." },
      { type: "formula", lines: ["30 000 zł kosztów stałych / 40% marży", "= 75 000 zł sprzedaży na próg rentowności"] },
      { type: "paragraph", text: "Przy sprzedaży poniżej 75 tys. firma traci. Przy 75 tys. wychodzi mniej więcej na zero. Powyżej tej wartości zaczyna zarabiać." },
      { type: "heading", text: "Możesz policzyć próg także w klientach lub zleceniach" },
      { type: "paragraph", text: "Jeśli średnio na jednym zleceniu pozostaje 3 tys. zł marży na pokrycie kosztów stałych, a koszty stałe wynoszą 30 tys., potrzebujesz około 10 zleceń miesięcznie." },
      { type: "callout", text: "Dziesięć zleceń pokrywa firmę. Jedenaste zaczyna zarabiać." },
      { type: "paragraph", text: "Próg rentowności jest szczególnie pomocny przed zwiększeniem kosztów stałych. Jeżeli zatrudnienie pracownika podniesie je z 30 do 40 tys., warto wcześniej policzyć, o ile musi wzrosnąć sprzedaż." }
    ]
  },
  {
    number: 17,
    slug: "czy-stac-mnie-na-pracownika",
    title: "Czy stać mnie na nowego pracownika?",
    excerpt: "Nie pytaj tylko o pensję. Policz pełny koszt i sprawdź, ile dodatkowej wartości musi powstać, aby zatrudnienie miało sens.",
    category: "Ludzie i koszty pracy",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Pytanie „Czy stać mnie na pracownika za 8 tys. zł brutto?” jest źle postawione. Prawdziwe pytanie brzmi: ile dodatkowej wartości ten pracownik musi wygenerować, aby zatrudnienie miało sens?" },
      { type: "paragraph", text: "Koszt firmy będzie wyższy od samego wynagrodzenia brutto. Dochodzą składki pracodawcy, sprzęt, miejsce pracy, systemy, szkolenia oraz czas wdrożenia. Do tego pracownik ma urlopy, może chorować i nie każda godzina jego pracy jest produktywna." },
      { type: "paragraph", text: "Załóżmy więc, że pełny miesięczny koszt zatrudnienia wynosi 12 tys. zł. Jeżeli firma osiąga 30% marży na dodatkowej sprzedaży, potrzeba około 40 tys. zł dodatkowej sprzedaży tylko po to, aby pokryć koszt pracownika." },
      { type: "formula", lines: ["12 000 zł pełnego kosztu / 30% marży", "= 40 000 zł dodatkowej sprzedaży"] },
      { type: "paragraph", text: "Ale pracownik może tworzyć wartość również inaczej. Może uwolnić czas właściciela, skrócić terminy realizacji, zmniejszyć liczbę błędów albo umożliwić przyjmowanie większej liczby klientów." },
      { type: "heading", text: "Decyzję oceń w dwóch wymiarach" },
      { type: "list", items: ["Koszt — stosunkowo łatwy do policzenia.", "Efekt — co ekonomicznie ma się zmienić dzięki zatrudnieniu."] },
      { type: "callout", text: "Najgorszy wariant to zatrudnienie „bo jest dużo pracy”, bez określenia, co ekonomicznie ma się dzięki temu zmienić." }
    ]
  },
  {
    number: 18,
    slug: "koszt-godziny-pracy",
    title: "Ile naprawdę kosztuje godzina pracy pracownika?",
    excerpt: "Pensja podzielona przez 168 godzin zwykle mocno zaniża koszt. W usługach liczy się koszt efektywnej godziny pracy.",
    category: "Ludzie i koszty pracy",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Pracownik zarabia 8 tys. zł brutto. Dzielimy przez około 168 godzin pracy miesięcznie. Wychodzi około 48 zł za godzinę. Czy tyle kosztuje firmę jego godzina? Nie." },
      { type: "paragraph", text: "Do wynagrodzenia dochodzą koszty pracodawcy. Ale to dopiero początek. Pracownik nie przepracuje produktywnie wszystkich godzin dostępnych w roku. Są urlopy, święta, szkolenia, choroby, spotkania, przerwy i czas organizacyjny." },
      { type: "paragraph", text: "Załóżmy, że całkowity miesięczny koszt pracownika wynosi 10 tys. zł. Nominalnie ma 168 godzin, ale rzeczywiście produktywnych godzin jest średnio 120." },
      { type: "formula", lines: ["10 000 zł całkowitego kosztu / 120 efektywnych godzin", "≈ 83 zł za efektywną godzinę"] },
      { type: "paragraph", text: "Jeżeli firma świadczy usługi, to bardzo ważna liczba. Sprzedawanie godziny pracy klientowi za 100 zł może wyglądać atrakcyjnie w stosunku do 48 zł wynagrodzenia brutto. Przy rzeczywistym koszcie 83 zł zostaje jednak tylko 17 zł na pokrycie administracji, biura, marketingu, sprzętu i zysku." },
      { type: "callout", text: "Do wyceny usług potrzebujemy kosztu efektywnej godziny pracy, a nie prostego podzielenia pensji przez liczbę godzin w miesiącu." }
    ]
  },
  {
    number: 19,
    slug: "jak-ustalic-cene",
    title: "Jak ustalić cenę, żeby nie pracować za darmo?",
    excerpt: "Cena nie powinna wynikać tylko z cennika konkurencji. Musi pokrywać koszt, koszty firmy, ryzyko i zostawiać miejsce na zysk.",
    category: "Cena i podatki",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Najprostsza metoda ustalania ceny wygląda tak: konkurencja bierze około 500 zł, więc my też ustawmy 500. Problem w tym, że nie wiesz, czy konkurencja na tej cenie zarabia. Nie wiesz też, czy ma takie same koszty." },
      { type: "heading", text: "Cena powinna uwzględniać co najmniej trzy rzeczy" },
      { type: "list", items: ["Koszt bezpośredni wykonania produktu lub usługi.", "Część kosztów funkcjonowania całej firmy.", "Zysk, który ma wynagrodzić właściciela za kapitał, ryzyko i rozwój biznesu."] },
      { type: "paragraph", text: "Załóżmy, że wykonanie usługi wymaga 10 godzin pracy po rzeczywistym koszcie 80 zł za godzinę. Koszt pracy to 800 zł. Do tego 200 zł innych kosztów. Łącznie 1000 zł." },
      { type: "paragraph", text: "Cena 1100 zł oznacza, że zostaje 100 zł. Czy to dużo? Nie wiemy. Z tych 100 zł trzeba jeszcze finansować marketing, księgowość, systemy IT, okresy bez zleceń i ryzyko reklamacji." },
      { type: "paragraph", text: "Dlatego „koszt + trochę” rzadko jest dobrą strategią. Cena powinna również uwzględniać wartość dla klienta. Jeżeli rozwiązujesz problem wart dla klienta 50 tys. zł, nie musisz wyceniać usługi wyłącznie na podstawie 10 godzin swojej pracy." },
      { type: "callout", label: "Trzy punkty odniesienia", text: "Najlepsza cena znajduje się gdzieś pomiędzy kosztem, wartością dla klienta i warunkami rynkowymi — a nie tylko w cenniku konkurencji." }
    ]
  },
  {
    number: 20,
    slug: "vat-nie-jest-przychodem",
    title: "VAT nie jest Twoim przychodem",
    excerpt: "Wpływ brutto na rachunek nie oznacza, że cała kwota jest sprzedażą ani wolną gotówką firmy.",
    category: "Cena i podatki",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Wystawiasz klientowi fakturę: 10 000 zł netto + VAT = kwota brutto do zapłaty. Klient przelewa całą kwotę brutto. Na rachunku pojawia się więcej pieniędzy niż wynosi Twoja sprzedaż netto." },
      { type: "paragraph", text: "To może tworzyć złudzenie, że firma ma więcej gotówki, niż rzeczywiście ma do dyspozycji." },
      { type: "paragraph", text: "VAT jest bowiem w uproszczeniu podatkiem, który przedsiębiorca pobiera w ramach transakcji, a następnie rozlicza z urzędem skarbowym, uwzględniając również VAT związany z zakupami." },
      { type: "paragraph", text: "Dlatego sprzedaż analizuje się zwykle w wartościach netto, jeżeli przedsiębiorca jest czynnym podatnikiem VAT i ma prawo do odpowiednich odliczeń." },
      { type: "paragraph", text: "Wyobraźmy sobie firmę, która przez kilka tygodni szybko rośnie. Na rachunek wpływają duże kwoty brutto. Saldo wygląda świetnie. Właściciel kupuje samochód albo wypłaca część pieniędzy." },
      { type: "paragraph", text: "Kilka tygodni później pojawia się termin rozliczenia VAT i okazuje się, że znaczna część gotówki była potrzebna do rozliczeń podatkowych." },
      { type: "heading", text: "Oddziel dwie rzeczy" },
      { type: "list", items: ["Pieniądze firmy.", "Pieniądze, które chwilowo znajdują się na rachunku firmy, ale będą potrzebne na podatki i inne zobowiązania."] },
      { type: "paragraph", text: "W szczegółach zasady rozliczania VAT mogą zależeć od rodzaju transakcji, sposobu rozliczeń i statusu podatnika. Z punktu widzenia zarządzania najważniejsza pozostaje jednak prosta zasada." },
      { type: "callout", text: "Wpływ brutto na rachunek nie oznacza, że cała otrzymana kwota jest przychodem ani wolną gotówką firmy." }
    ]
  },
  {
    number: 0,
    slug: "czym-powinien-byc-wspolczesny-controlling",
    title: "Czym powinien być współczesny controlling?",
    excerpt: "Rama dla całej serii: controlling jako system łączący strategię, dane, kontekst i decyzje — a dopiero potem technologię.",
    category: "Controlling × AI",
    track: "controlling-ai",
    readTime: "5 min",
    blocks: [
      { type: "lead", text: "W wielu firmach controlling nadal kojarzy się przede wszystkim z budżetem, raportem miesięcznym i analizą odchyleń." },
      { type: "paragraph", text: "Zamykamy miesiąc. Porównujemy „Actual vs. Budget”. Przygotowujemy komentarze. Raport trafia do zarządu." },
      { type: "paragraph", text: "To potrzebne elementy controllingu. Ale moim zdaniem nie definiują jego istoty." },
      { type: "callout", label: "Punkt wyjścia", text: "Controlling powinien być systemem wspierającym podejmowanie decyzji." },
      { type: "paragraph", text: "Jeżeli nie pomaga organizacji szybciej zauważać problemów, rozumieć ich przyczyn, przewidywać konsekwencji i wybierać między alternatywami, staje się w najlepszym wypadku sprawnym systemem raportowania przeszłości." },
      { type: "paragraph", text: "A to za mało." },
      { type: "heading", text: "Od strategii do decyzji" },
      { type: "paragraph", text: "Firma może chcieć rosnąć szybciej niż rynek, poprawić rentowność, generować więcej gotówki, ograniczyć zadłużenie albo zwiększyć produktywność." },
      { type: "paragraph", text: "Jeżeli chcemy poprawić rentowność, musimy wiedzieć, co ją napędza: cena, mix produktów, koszt zakupu, produktywność, wykorzystanie zasobów czy rentowność klientów." },
      { type: "paragraph", text: "Strategia mówi, **dokąd chcemy dojść**." },
      { type: "paragraph", text: "Controlling powinien mówić **czy tam zmierzamy.** A jeśli nie, to dlaczego i co możemy zrobić, aby wrócić na właściwą ścieżkę." },
      { type: "heading", text: "Cztery pytania" },
      { type: "paragraph", text: "Dobry system controllingowy powinien odpowiadać kolejno na cztery pytania." },
      { type: "heading", text: "Co się wydarzyło?" },
      { type: "paragraph", text: "Sprzedaż spadła o 8%. Marża pogorszyła się o 1,4 punktu procentowego." },
      { type: "paragraph", text: "To klasyczna warstwa raportowa." },
      { type: "heading", text: "Dlaczego?" },
      { type: "paragraph", text: "Cena? Wolumen? Mix? Koszt surowca? Jeden duży klient?" },
      { type: "paragraph", text: "Taką wiedzę może nam dostarczyć rachunkowość odchyleń („variance analysis”)." },
      { type: "heading", text: "Co prawdopodobnie wydarzy się dalej?" },
      { type: "paragraph", text: "Jeżeli obecne trendy się utrzymają, gdzie będziemy za trzy miesiące? Jak wygląda realizacja forecastu? Czy powstaje ryzyko dla wyniku lub płynności?" },
      { type: "heading", text: "Co możemy zrobić?" },
      { type: "paragraph", text: "Podnieść ceny? Zmienić mix? Ograniczyć koszty? Renegocjować zakupy?" },
      { type: "paragraph", text: "Controlling nie powinien podejmować decyzji za managera. Powinien jednak pokazać możliwe warianty i ich konsekwencje." },
      { type: "heading", text: "Finanse są skutkiem biznesu" },
      { type: "paragraph", text: "Firma w swojej istocie nie jest systemem finansowym." },
      { type: "paragraph", text: "Wynik finansowy jest rezultatem tego, co wydarzyło się wcześniej w sprzedaży, produkcji, zakupach, logistyce czy zatrudnieniu." },
      { type: "paragraph", text: "Dlatego współczesny controlling powinien łączyć:" },
      { type: "paragraph", text: "**dane finansowe** — co stało się z wynikiem," },
      { type: "paragraph", text: "**dane operacyjne** — co wydarzyło się w biznesie," },
      { type: "paragraph", text: "**informacje o przyszłości** — pipeline, zamówienia, kontrakty, ceny, moce, zatrudnienie, plany i scenariusze," },
      { type: "paragraph", text: "**informacje o strukturze, powiązaniach, zakresach odpowiedzialności, ograniczeniach, warunkach brzegowych** — czyli indywidualny kontekst każdej organizacji." },
      { type: "paragraph", text: "Powinien również uwzględniać **dane zewnętrzne**: kursy walut, ceny surowców czy dane rynkowe." },
      { type: "paragraph", text: "Dopiero wtedy zaczynamy rozumieć mechanikę biznesu, a nie tylko jego rezultat." },
      { type: "heading", text: "Informacja musi pojawić się na czas" },
      { type: "paragraph", text: "Nie każda informacja musi być dostępna w czasie rzeczywistym." },
      { type: "paragraph", text: "Ale powinna pojawić się **wystarczająco wcześnie, aby można było jeszcze coś zrobić**." },
      { type: "paragraph", text: "Strategia może wymagać analizy kwartalnej." },
      { type: "paragraph", text: "Płynność — tygodniowej." },
      { type: "paragraph", text: "Sprzedaż — dziennej lub tygodniowej." },
      { type: "paragraph", text: "Dobre pytanie brzmi więc nie:" },
      { type: "paragraph", text: "Jak często przygotowujemy raport?" },
      { type: "paragraph", text: "ale:" },
      { type: "callout", text: "Jak szybko musimy wiedzieć o zmianie, żeby móc zareagować?" },
      { type: "heading", text: "Od KPI do działania" },
      { type: "paragraph", text: "Nie chodzi też o liczbę wskaźników." },
      { type: "paragraph", text: "Dobrym testem KPI jest pytanie:" },
      { type: "paragraph", text: "Jeśli ten wskaźnik się zmieni, jaką decyzję możemy podjąć?" },
      { type: "paragraph", text: "Dlatego architekturę controllingu warto budować w kolejności:" },
      { type: "formula", lines: ["cel → decyzja → driver biznesowy → KPI → próg/alert → działanie."] },
      { type: "paragraph", text: "To znacznie lepszy punkt wyjścia niż:" },
      { type: "paragraph", text: "mamy dużo danych — zastanówmy się, jakie raporty możemy z nich zrobić." },
      { type: "heading", text: "A gdzie jest AI?" },
      { type: "paragraph", text: "Dopiero tutaj." },
      { type: "paragraph", text: "Jeżeli wiemy, jakie decyzje chcemy wspierać, jakie są kluczowe drivery, komu dostarczać informacje i z jaką szybkością, możemy zapytać:" },
      { type: "callout", text: "które elementy tego systemu AI może zrobić szybciej, szerzej albo lepiej?" },
      { type: "paragraph", text: "AI może analizować większą liczbę danych, wykrywać anomalie, przygotowywać hipotezy, generować komentarze, wspierać forecasting i scenariusze." },
      { type: "paragraph", text: "Ale pozostaje elementem systemu." },
      { type: "paragraph", text: "Nie jego substytutem!" },
      { type: "paragraph", text: "Moja robocza definicja współczesnego controllingu jest więc prosta:" },
      { type: "callout", label: "Definicja robocza", text: "Controlling łączy cele firmy, dane i wiedzę biznesową po to, aby właściwa osoba otrzymała właściwą informację wystarczająco wcześnie, by podjąć lepszą decyzję." },
      { type: "paragraph", text: "Ostateczny test brzmi:" },
      { type: "callout", text: "Czy dzięki controllingowi organizacja podejmuje lepsze decyzje?" },
      { type: "paragraph", text: "Od tego warto zacząć rozmowę o AI." }
    ]
  },
  {
    number: 1,
    slug: "ai-w-controllingu-od-czego-zaczac",
    title: "AI w controllingu: od czego naprawdę warto zacząć?",
    excerpt: "Od problemu decyzyjnego, nie od modelu AI. Jak wybierać pierwsze zastosowania według wartości, danych, wykonalności i ryzyka.",
    category: "Controlling × AI",
    track: "controlling-ai",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Zanim zaczniemy szukać zastosowań AI, powinniśmy wiedzieć, jaki controlling chcemy zbudować." },
      { type: "paragraph", text: "Jeżeli jego rolą jest wspieranie decyzji, technologię należy oceniać według tego, czy pomaga tę funkcję realizować lepiej — a nie według liczby procesów, które potrafimy zautomatyzować." },
      { type: "paragraph", text: "Dlatego pierwsze pytanie nie powinno brzmieć:" },
      { type: "paragraph", text: "Jakiego modelu albo narzędzia AI użyć?" },
      { type: "paragraph", text: "Lepiej zapytać:" },
      { type: "callout", text: "Który fragment procesu decyzyjnego działa dziś zbyt wolno, kosztuje zbyt dużo pracy albo dostarcza zbyt mało wartości?" },
      { type: "heading", text: "AI nie zawsze jest najlepszą odpowiedzią" },
      { type: "paragraph", text: "Jeżeli controller przez dwie godziny kopiuje dane pomiędzy plikami, rozwiązaniem może być Power Query, integracja systemów albo zwykła automatyzacja." },
      { type: "paragraph", text: "Model językowy nie jest potrzebny do wszystkiego." },
      { type: "paragraph", text: "Jeżeli jednak controller ma kilkaset linii P&L, kilkanaście jednostek biznesowych, dane sprzedażowe i trzy godziny na znalezienie najważniejszych zmian oraz przygotowanie komentarza dla zarządu, AI zaczyna mieć znacznie więcej sensu." },
      { type: "heading", text: "Dobry pierwszy use case" },
      { type: "paragraph", text: "Szukając pierwszych zastosowań, patrzyłbym na cztery elementy." },
      { type: "paragraph", text: "**Wartość biznesowa.** Czy wynik procesu rzeczywiście wspiera istotną decyzję?" },
      { type: "paragraph", text: "**Jakość danych.** Czy dane są wystarczająco spójne, żeby można było im zaufać?" },
      { type: "paragraph", text: "**Wykonalność.** Czy można zbudować rozwiązanie w rozsądnym czasie i koszcie?" },
      { type: "paragraph", text: "**Ryzyko.** Jak poważne będą konsekwencje błędnej odpowiedzi?" },
      { type: "paragraph", text: "Dobrym początkiem są procesy, w których wynik AI może łatwo zweryfikować człowiek." },
      { type: "paragraph", text: "Dlatego pierwszym projektem chętniej zrobiłbym automatyczny draft komentarza do wyników niż autonomiczny system rekomendujący wielomilionowe inwestycje." },
      { type: "heading", text: "Gdzie szukać?" },
      { type: "paragraph", text: "Najczęściej w miejscach takich jak:" },
      { type: "paragraph", text: "analiza odchyleń, przygotowanie komentarzy, wykrywanie anomalii, kontrola jakości danych, przygotowanie danych do forecastu czy analiza wielu wymiarów jednocześnie." },
      { type: "paragraph", text: "To zwykle obszary, w których controller wykonuje dużą ilość pracy mechanicznej zanim rozpocznie właściwą analizę." },
      { type: "paragraph", text: "Jeżeli AI skróci przygotowanie informacji z sześciu godzin do jednej, nie chodzi o to, żeby controller przygotowywał sześć razy więcej raportów." },
      { type: "paragraph", text: "Powinien wykorzystać odzyskany czas na sprawdzenie hipotez, rozmowę z biznesem i rekomendacje." },
      { type: "paragraph", text: "To właśnie jest dla mnie istota wartości AI w controllingu:" },
      { type: "callout", text: "mniej czasu na przygotowanie informacji, więcej na jej zrozumienie i wykorzystanie." }
    ]
  },
  {
    number: 2,
    slug: "zanim-wdrozysz-ai-sprawdz-controlling",
    title: "Zanim wdrożysz AI, sprawdź, gdzie Twój controlling nie spełnia swojej roli",
    excerpt: "AI może przyspieszyć dobry proces, ale również zły. Jak rozpoznać, gdzie system informacji zarządczej wymaga poprawy przed automatyzacją.",
    category: "Controlling × AI",
    track: "controlling-ai",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "AI nie naprawi źle zaprojektowanego controllingu." },
      { type: "paragraph", text: "Jeżeli dwa działy inaczej rozumieją marżę, raport miesięczny ma 70 stron, forecast powstaje przez dwa tygodnie, a część zestawień nie prowadzi do żadnej decyzji, zastosowanie AI może jedynie przyspieszyć produkowanie niewłaściwej informacji." },
      { type: "paragraph", text: "Dlatego przed wdrożeniem technologii warto zapytać:" },
      { type: "callout", text: "Gdzie obecny controlling nie dostarcza informacji potrzebnej do podjęcia decyzji?" },
      { type: "paragraph", text: "Może dostarcza ją za późno." },
      { type: "paragraph", text: "Może pokazuje skutek, ale nie przyczynę." },
      { type: "paragraph", text: "Może daje managerowi 40 KPI zamiast trzech rzeczy wymagających uwagi." },
      { type: "paragraph", text: "A czasami raportuje coś, czego nikt nie wykorzystuje." },
      { type: "heading", text: "Technologia często odsłania problemy organizacyjne" },
      { type: "paragraph", text: "Załóżmy, że firma chce stworzyć chatbota odpowiadającego managerom na pytania o wyniki." },
      { type: "paragraph", text: "Szybko okazuje się, że sprzedaż w CRM różni się od ERP, EBITDA w różnych raportach ma inną definicję, a struktura produktów w planie różni się od actual." },
      { type: "paragraph", text: "To nie jest problem LLM." },
      { type: "paragraph", text: "To problem governance i modelu danych." },
      { type: "paragraph", text: "AI nie wie, która definicja jest prawidłowa, jeżeli organizacja sama tego nie ustaliła." },
      { type: "heading", text: "Zrób test raportów" },
      { type: "paragraph", text: "Dla każdego ważniejszego raportu warto zadać cztery pytania:" },
      { type: "paragraph", text: "Kto go używa?" },
      { type: "paragraph", text: "Jaką decyzję na jego podstawie podejmuje?" },
      { type: "paragraph", text: "Która informacja jest naprawdę potrzebna?" },
      { type: "paragraph", text: "Co stanie się, jeśli raport przestaniemy przygotowywać?" },
      { type: "paragraph", text: "Jeśli na ostatnie pytanie odpowiedź brzmi:" },
      { type: "paragraph", text: "właściwie nic," },
      { type: "paragraph", text: "to prawdopodobnie znaleźliśmy lepszego kandydata do usunięcia niż do automatyzacji." },
      { type: "heading", text: "Nie potrzebujemy perfekcji" },
      { type: "paragraph", text: "Nie oznacza to, że przed wykorzystaniem AI trzeba przez dwa lata budować idealną hurtownię danych." },
      { type: "paragraph", text: "Potrzebujemy jedynie wystarczającego porządku w konkretnym obszarze." },
      { type: "paragraph", text: "Jeżeli chcemy automatycznie analizować koszty marketingu, potrzebujemy spójnej klasyfikacji kosztów, danych actual, planu lub forecastu oraz kontekstu potrzebnego do interpretacji odchyleń." },
      { type: "paragraph", text: "To może wystarczyć do pierwszego prototypu." },
      { type: "paragraph", text: "Co ciekawe, próba wdrożenia AI często sama staje się bardzo dobrą diagnostyką controllingu." },
      { type: "paragraph", text: "Model zaczyna ujawniać pytania, których wcześniej nie zadawaliśmy:" },
      { type: "paragraph", text: "Która definicja marży obowiązuje?" },
      { type: "paragraph", text: "Który forecast jest aktualny?" },
      { type: "paragraph", text: "Dlaczego ten sam klient ma trzy identyfikatory?" },
      { type: "paragraph", text: "To cenna wiedza." },
      { type: "paragraph", text: "Dlatego zanim zapytamy:" },
      { type: "paragraph", text: "gdzie wdrożyć AI?" },
      { type: "paragraph", text: "warto najpierw ustalić:" },
      { type: "callout", text: "co w naszym obecnym systemie informacji zarządczej naprawdę wymaga poprawy?" }
    ]
  },
  {
    number: 3,
    slug: "controller-z-ai-czy-ai-zamiast-controllera",
    title: "Controller z AI czy AI zamiast controllera?",
    excerpt: "Automatyzacja zmieni pracę controllera, ale nie usuwa potrzeby kontekstu, oceny i odpowiedzialności za rekomendację.",
    category: "Controlling × AI",
    track: "controlling-ai",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Jeżeli controlling ma być systemem wspierającym decyzje, również rolę controllera trzeba oceniać przez ten pryzmat." },
      { type: "paragraph", text: "Nie chodzi przede wszystkim o to, które zadania człowieka można technicznie zautomatyzować." },
      { type: "paragraph", text: "Ważniejsze pytanie brzmi:" },
      { type: "callout", text: "Gdzie kompetencje człowieka tworzą największą wartość w procesie podejmowania decyzji?" },
      { type: "heading", text: "Co technologia może przejąć?" },
      { type: "paragraph", text: "Znaczną część pracy controllingu stanowią czynności powtarzalne:" },
      { type: "paragraph", text: "zbieranie danych, porównywanie okresów, wyszukiwanie odchyleń, identyfikowanie anomalii, przygotowanie pierwszej wersji komentarzy czy prezentacji." },
      { type: "paragraph", text: "AI może np. przeanalizować kilkaset pozycji kosztowych i wskazać kilkanaście, które najbardziej wpłynęły na zmianę wyniku." },
      { type: "paragraph", text: "Może przygotować draft:" },
      { type: "paragraph", text: "Koszty logistyki były o 8% powyżej forecastu, głównie wskutek wzrostu kosztów transportu w regionie X." },
      { type: "paragraph", text: "Controller nie musi zaczynać od pustej kartki." },
      { type: "heading", text: "Gdzie potrzebny jest człowiek?" },
      { type: "paragraph", text: "Sprzedaż spadła o 7%." },
      { type: "paragraph", text: "System widzi liczbę." },
      { type: "paragraph", text: "Controller może wiedzieć, że kluczowy klient przesunął zamówienie o miesiąc i nie ma powodów do niepokoju." },
      { type: "paragraph", text: "Albo odwrotnie — pozornie małe odchylenie może być pierwszym sygnałem poważniejszego problemu." },
      { type: "paragraph", text: "Potrzebne są wtedy:" },
      { type: "paragraph", text: "kontekst biznesowy, doświadczenie, rozmowa z managerem, ocena ryzyka i odpowiedzialność za rekomendację." },
      { type: "heading", text: "Rola controllera będzie się przesuwać" },
      { type: "paragraph", text: "Przez lata część wartości controllera wynikała z tego, że potrafił zdobyć dane, połączyć je i przygotować raport." },
      { type: "paragraph", text: "Ta przewaga będzie maleć." },
      { type: "paragraph", text: "Jeżeli manager może zapytać:" },
      { type: "paragraph", text: "Dlaczego marża spadła w regionie północnym?" },
      { type: "paragraph", text: "i dostać sensowną analizę w kilkanaście sekund, controller musi wnosić coś więcej." },
      { type: "paragraph", text: "Jego wartością staje się:" },
      { type: "paragraph", text: "weryfikowanie informacji, rozumienie zależności, budowanie scenariuszy, kwestionowanie założeń i wspieranie decyzji." },
      { type: "paragraph", text: "AI może więc paradoksalnie wzmocnić zawód controllera." },
      { type: "paragraph", text: "Pod warunkiem, że controller nie definiuje swojej wartości przez umiejętność produkowania raportu." },
      { type: "paragraph", text: "Przyszłość nie sprowadza się do wyboru:" },
      { type: "callout", text: "człowiek albo AI." },
      { type: "paragraph", text: "Bardziej interesujące pytanie brzmi:" },
      { type: "callout", text: "Jak wygląda controller, który dzięki AI może poświęcić więcej czasu na rzeczy, w których człowiek naprawdę tworzy wartość?" }
    ]
  },
  {
    number: 4,
    slug: "procesy-controllingowe-automatyzacja-80-20",
    title: "Jak znaleźć 20% procesów controllingowych, których automatyzacja da 80% efektu",
    excerpt: "Praktyczna metoda wyboru procesów, w których automatyzacja daje wysoką wartość decyzyjną i realnie odzyskuje czas zespołu.",
    category: "Controlling × AI",
    track: "controlling-ai",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Nie każdy proces warto automatyzować." },
      { type: "paragraph", text: "I nie każdy proces, który można zautomatyzować, warto zachować." },
      { type: "paragraph", text: "To ważne rozróżnienie." },
      { type: "paragraph", text: "Możemy bardzo efektywnie zautomatyzować raport, którego nikt nie potrzebuje." },
      { type: "paragraph", text: "Dlatego wartość projektu powinna być oceniana nie tylko przez oszczędność czasu." },
      { type: "heading", text: "Zacznij od mapy pracy" },
      { type: "paragraph", text: "Poprosiłbym zespół controllingu o zapisanie przez tydzień lub dwa, na co faktycznie poświęca czas." },
      { type: "paragraph", text: "Nie:" },
      { type: "paragraph", text: "reporting — 30% czasu," },
      { type: "paragraph", text: "ale:" },
      { type: "paragraph", text: "kopiowanie danych z ERP — 2 h," },
      { type: "paragraph", text: "uzgadnianie różnic — 1,5 h," },
      { type: "paragraph", text: "komentarz do” variance” — 3 h," },
      { type: "paragraph", text: "aktualizacja „forecastu” — 5 h." },
      { type: "paragraph", text: "Taka mapa szybko pokazuje, gdzie naprawdę idzie główny wysiłek zespołu controllingowego." },
      { type: "heading", text: "Potem zastosuj prostą macierz" },
      { type: "paragraph", text: "Każdy proces można ocenić według czterech kryteriów:" },
      { type: "paragraph", text: "**wartość decyzyjna** — czy wspiera ważną decyzję," },
      { type: "paragraph", text: "**oszczędność pracy** — ile czasu możemy odzyskać," },
      { type: "paragraph", text: "**wykonalność** — czy mamy dane i technologię," },
      { type: "paragraph", text: "**ryzyko** — co się stanie, jeśli rozwiązanie popełni błąd." },
      { type: "paragraph", text: "Możemy to zapisać:" },
      { type: "formula", lines: ["wartość decyzyjna × oszczędność pracy × wykonalność × ryzyko"] },
      { type: "paragraph", text: "Najlepsze pierwsze projekty mają wysoką wartość, są stosunkowo proste i łatwe do kontrolowania. Wysokie ryzyko nie oznacza, że nie powinniśmy wdrażać automatyzacji. Jest to tylko wskazówka, że powinniśmy zapewnić odpowiedni poziom nadzoru." },
      { type: "heading", text: "Nie potrzebujemy pełnej automatyzacji" },
      { type: "paragraph", text: "Celem rzadko powinno być:" },
      { type: "paragraph", text: "100% procesu wykonuje system." },
      { type: "paragraph", text: "Znacznie częściej sensowny wariant to:" },
      { type: "paragraph", text: "maszyna wykonuje 70% powtarzalnej pracy, człowiek 30% wymagające oceny." },
      { type: "paragraph", text: "To często daje większość efektu przy dużo niższym ryzyku." },
      { type: "paragraph", text: "Najlepszych zastosowań AI szukałbym więc nie tam, gdzie można zrobić najbardziej efektowne demo." },
      { type: "paragraph", text: "Szukałbym **tarcia organizacyjnego**." },
      { type: "paragraph", text: "Miejsc, gdzie doświadczeni ludzie wykonują mechaniczne czynności, zamiast wykorzystywać swoją wiedzę do analizy i decyzji." }
    ]
  },
  {
    number: 5,
    slug: "ai-generated-management-commentary",
    title: "AI-generated management commentary: 30 minut zamiast pół dnia?",
    excerpt: "Jak AI może przygotować pierwszą wersję komentarza do wyników — i dlaczego fakt, hipoteza oraz kontrola człowieka muszą pozostać rozdzielone.",
    category: "Controlling × AI",
    track: "controlling-ai",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Komentarz miesięczny ma sens tylko wtedy, gdy pomaga odbiorcy przejść od liczby do jej znaczenia." },
      { type: "paragraph", text: "Automatyczne wygenerowanie zdania:" },
      { type: "paragraph", text: "Costs +8% vs Budget" },
      { type: "paragraph", text: "tworzy niewielką wartość." },
      { type: "paragraph", text: "Ciekawie robi się wtedy, gdy system potrafi wskazać, **które odchylenia są istotne, skąd wynikają i które wymagają uwagi**." },
      { type: "heading", text: "Jak wygląda tradycyjny proces?" },
      { type: "paragraph", text: "Controller otrzymuje actual (wykonanie), porównuje go z budgetem, forecastem i poprzednim rokiem." },
      { type: "paragraph", text: "Przegląda P&L, sprzedaż i KPI." },
      { type: "paragraph", text: "Wyszukuje największe odchylenia." },
      { type: "paragraph", text: "Potem zaczyna pisać komentarz." },
      { type: "paragraph", text: "Duża część tej pracy jest powtarzalna." },
      { type: "heading", text: "Co może zrobić AI?" },
      { type: "paragraph", text: "System może otrzymać dane Actual, Budget, Forecast, Previous Year oraz odpowiednie dane operacyjne." },
      { type: "paragraph", text: "Następnie może:" },
      { type: "paragraph", text: "wybrać istotne odchylenia, uszeregować je według wpływu na wynik, połączyć powiązane zmiany i przygotować pierwszą wersję narracji." },
      { type: "paragraph", text: "Na przykład:" },
      { type: "paragraph", text: "EBITDA była o 1,2 mln zł poniżej forecastu. Główne negatywne czynniki to niższa marża brutto oraz wyższe koszty personalne, częściowo skompensowane niższymi kosztami marketingu." },
      { type: "paragraph", text: "To można przygotować bardzo szybko." },
      { type: "heading", text: "Gdzie zaczyna się ryzyko?" },
      { type: "paragraph", text: "LLM może stworzyć zdanie brzmiące przekonująco, mimo że interpretacja jest błędna." },
      { type: "paragraph", text: "Dlatego trzeba rozdzielić:" },
      { type: "paragraph", text: "**fakt wynikający z danych** od **hipotezy dotyczącej przyczyny**." },
      { type: "paragraph", text: "System może policzyć:" },
      { type: "paragraph", text: "70% odchylenia pochodzi z regionu X." },
      { type: "paragraph", text: "Nie powinien bez dodatkowych danych twierdzić:" },
      { type: "paragraph", text: "przyczyną była agresywna polityka cenowa konkurenta." },
      { type: "heading", text: "Human-in-the-loop" },
      { type: "paragraph", text: "Najbezpieczniejszy jest system hybrydowy." },
      { type: "paragraph", text: "AI przygotowuje draft." },
      { type: "paragraph", text: "Controller sprawdza liczby, potwierdza logikę, dodaje kontekst i usuwa nieuzasadnione wnioski." },
      { type: "paragraph", text: "Dopiero wtedy komentarz trafia do zarządu." },
      { type: "paragraph", text: "W takim modelu AI nie zastępuje controllera." },
      { type: "paragraph", text: "Usuwa z jego pracy pustą kartkę i dużą część mechanicznej analizy." },
      { type: "paragraph", text: "To może być jeden z najbardziej praktycznych pierwszych use case'ów AI w controllingu." }
    ]
  },
  {
    number: 6,
    slug: "variance-analysis-root-cause-analysis",
    title: "Od “variance analysis” do “root cause analysis”. Jak przejść od „co?” do „co możemy zrobić?”",
    excerpt: "Od odchylenia przez przyczynę i oczekiwany wpływ do możliwego działania: jak pogłębić analizę bez mnożenia raportów.",
    category: "Controlling × AI",
    track: "controlling-ai",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Klasyczny raport dobrze odpowiada na pytanie:" },
      { type: "paragraph", text: "Co się zmieniło?" },
      { type: "paragraph", text: "Sprzedaż -8%." },
      { type: "paragraph", text: "Marża -1,4 p.p." },
      { type: "paragraph", text: "Koszty personalne +6%." },
      { type: "paragraph", text: "Ale dla managera jest to dopiero początek." },
      { type: "paragraph", text: "Prawdziwa wartość pojawia się wtedy, gdy możemy przejść przez cały ciąg:" },
      { type: "formula", lines: ["variance → root cause → expected impact → possible action"] },
      { type: "heading", text: "Jedno odchylenie może mieć wiele przyczyn" },
      { type: "paragraph", text: "Marża brutto spadła z 32% do 29%." },
      { type: "paragraph", text: "Może to wynikać z:" },
      { type: "paragraph", text: "ceny, kosztu zakupu, mixu produktów, klientów, kursu walutowego, transportu albo struktury geograficznej sprzedaży." },
      { type: "paragraph", text: "Każda przyczyna wymaga innej reakcji." },
      { type: "paragraph", text: "Dlatego samo:" },
      { type: "paragraph", text: "marża -3 p.p." },
      { type: "paragraph", text: "ma ograniczoną wartość zarządczą." },
      { type: "heading", text: "Problemem jest liczba możliwych kombinacji" },
      { type: "paragraph", text: "Controller może analizować produkty, klientów, regiony i kanały." },
      { type: "paragraph", text: "Ale wraz z liczbą wymiarów rośnie liczba potencjalnych zależności." },
      { type: "paragraph", text: "Tutaj AI i klasyczna analityka mogą się dobrze uzupełniać." },
      { type: "paragraph", text: "System może sprawdzić, które produkty odpowiadają za największą część spadku, czy problem dotyczy kilku klientów, czy jest lokalny oraz czy pojawił się nagle czy narastał przez kilka miesięcy." },
      { type: "heading", text: "Dalej niż root cause" },
      { type: "paragraph", text: "Załóżmy, że analiza pokazuje:" },
      { type: "paragraph", text: "62% spadku marży wynika ze zmiany mixu w kierunku produktów o niższej rentowności." },
      { type: "paragraph", text: "To już dużo." },
      { type: "paragraph", text: "Ale można pójść dalej:" },
      { type: "paragraph", text: "Jeżeli obecny mix utrzyma się do końca roku, wpływ na wynik wyniesie około X." },
      { type: "paragraph", text: "A potem:" },
      { type: "paragraph", text: "Możliwe działania to zmiana cen, ograniczenie promocji lub zwiększenie sprzedaży produktów o wyższej marży." },
      { type: "paragraph", text: "Nie oznacza to, że AI powinno samodzielnie wybrać działanie." },
      { type: "paragraph", text: "Może natomiast pomóc przejść od symptomu przez przyczynę do scenariuszy reakcji." },
      { type: "paragraph", text: "I właśnie wtedy raport przestaje być opisem historii." },
      { type: "paragraph", text: "Staje się narzędziem zarządzania." }
    ]
  },
  {
    number: 7,
    slug: "rolling-forecast-z-ai",
    title: "Rolling forecast z AI: czy można prognozować lepiej, nie budując większego Excela?",
    excerpt: "Forecast jako system aktualizacji wiedzy o przyszłości. Gdzie AI pomaga, a gdzie lepsze pozostają modele statystyczne i biznesowe drivery.",
    category: "Controlling × AI",
    track: "controlling-ai",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Forecast nie powinien być kolejną wersją budżetu." },
      { type: "paragraph", text: "Powinien być **systemem aktualizacji wiedzy o przyszłości**." },
      { type: "paragraph", text: "W wielu firmach wygląda jednak podobnie." },
      { type: "paragraph", text: "Centrala wysyła szablon. Jednostki wpisują liczby. Controlling konsoliduje pliki. Trwają rundy korekt." },
      { type: "paragraph", text: "Po dwóch tygodniach mamy nowy forecast." },
      { type: "paragraph", text: "Po kolejnych dwóch część założeń jest już nieaktualna." },
      { type: "heading", text: "Forecast nie powinien udawać pewności" },
      { type: "paragraph", text: "Jego rolą nie jest przewidzenie przyszłości z dokładnością do złotówki." },
      { type: "paragraph", text: "Ma odpowiedzieć:" },
      { type: "paragraph", text: "Dokąd zmierza biznes?" },
      { type: "paragraph", text: "Które założenia są najważniejsze?" },
      { type: "paragraph", text: "Jakie ryzyka pojawiają się na horyzoncie?" },
      { type: "paragraph", text: "Jak wyglądają alternatywne scenariusze?" },
      { type: "heading", text: "Gdzie może pomóc AI?" },
      { type: "paragraph", text: "Pierwszy poziom to przygotowanie **baseline**." },
      { type: "paragraph", text: "Dla wielu pozycji można wykorzystać historię, sezonowość i biznesowe drivery." },
      { type: "paragraph", text: "Do samego prognozowania szeregu czasowego LLM nie zawsze jest najlepszym narzędziem. Lepsze mogą być klasyczne modele statystyczne lub machine learning." },
      { type: "paragraph", text: "LLM może jednak pomóc interpretować wynik i pracować z założeniami." },
      { type: "heading", text: "AI jako challenge" },
      { type: "paragraph", text: "Manager prognozuje wzrost sprzedaży o 12%." },
      { type: "paragraph", text: "System może zauważyć:" },
      { type: "paragraph", text: "W ostatnich sześciu miesiącach wolumen wzrastał średnio o 3%. Jakie konkretne zdarzenie uzasadnia przyjęcie 12%?" },
      { type: "paragraph", text: "To ciekawe wykorzystanie AI." },
      { type: "paragraph", text: "Nie tworzenie liczby." },
      { type: "callout", text: "Kwestionowanie liczby." },
      { type: "heading", text: "Częstotliwość powinna wynikać z biznesu" },
      { type: "paragraph", text: "Forecast nie powinien być aktualizowany dlatego, że „wypadł kolejny cykl”." },
      { type: "paragraph", text: "Powinien zmieniać się wtedy, kiedy zmieniają się istotne informacje." },
      { type: "paragraph", text: "Duży klient ogranicza zamówienia." },
      { type: "paragraph", text: "Pipeline słabnie." },
      { type: "paragraph", text: "Cena surowca rośnie." },
      { type: "paragraph", text: "Rotacja personelu zwiększa się." },
      { type: "paragraph", text: "Jeżeli informacje te istotnie zmieniają perspektywę wyniku, system powinien to pokazać." },
      { type: "paragraph", text: "Częstotliwość forecastu powinna więc wynikać **z szybkości zmian biznesu, a nie z kalendarza controllingu**." },
      { type: "paragraph", text: "AI nie usuwa niepewności." },
      { type: "paragraph", text: "Może jednak pomóc wcześniej zobaczyć, że przyjęty wcześniej obraz przyszłości przestaje być aktualny." }
    ]
  },
  {
    number: 8,
    slug: "excel-power-bi-llm-architektura-controllingu",
    title: "Excel, Power BI i LLM — jak zbudować sensowną architekturę informacji dla controllingu",
    excerpt: "Excel, BI i LLM nie muszą konkurować. Każde narzędzie ma inną rolę w architekturze informacji prowadzącej od danych do decyzji.",
    category: "Controlling × AI",
    track: "controlling-ai",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Nie zaczynałbym od pytania:" },
      { type: "paragraph", text: "Czy AI zastąpi Excela?" },
      { type: "paragraph", text: "Ani:" },
      { type: "paragraph", text: "Czy potrzebujemy Power BI, czy LLM?" },
      { type: "paragraph", text: "Najpierw zapytałbym:" },
      { type: "callout", text: "Jakiej architektury informacji potrzebujemy, aby wspierać decyzje?" },
      { type: "paragraph", text: "Dopiero potem dobierałbym narzędzia." },
      { type: "heading", text: "Źródła i model danych" },
      { type: "paragraph", text: "Na dole znajdują się ERP, CRM i systemy operacyjne." },
      { type: "paragraph", text: "To tam powstają dane źródłowe." },
      { type: "paragraph", text: "Następna warstwa powinna zapewniać ich spójność, historię i możliwość łączenia." },
      { type: "paragraph", text: "Tu wchodzi hurtownia lub inny uporządkowany model danych." },
      { type: "heading", text: "Jedno znaczenie pojęć" },
      { type: "paragraph", text: "Kolejnym elementem jest warstwa semantyczna." },
      { type: "paragraph", text: "Jeżeli „Net Sales”, „Gross Margin” albo „Active Customer” mają być używane przez ludzi i AI, organizacja potrzebuje jednoznacznych definicji." },
      { type: "paragraph", text: "Bez tego można otrzymywać technicznie poprawne odpowiedzi na źle zdefiniowane pytania." },
      { type: "heading", text: "Excel" },
      { type: "paragraph", text: "Excel pozostaje bardzo dobrym narzędziem do:" },
      { type: "paragraph", text: "modelowania ad hoc, analiz scenariuszowych, obliczeń i prototypowania." },
      { type: "paragraph", text: "Problem powstaje, gdy staje się jednocześnie bazą danych, workflow, systemem raportowym i jedynym miejscem, w którym jedna osoba rozumie całą logikę." },
      { type: "heading", text: "BI" },
      { type: "paragraph", text: "Power BI i podobne narzędzia świetnie sprawdzają się w standaryzowanej dystrybucji i wizualizacji informacji." },
      { type: "paragraph", text: "Nie rozwiązują jednak automatycznie problemu interpretacji." },
      { type: "paragraph", text: "20 wykresów nadal wymaga od managera wiedzy, gdzie patrzeć." },
      { type: "heading", text: "LLM" },
      { type: "paragraph", text: "Model językowy może być warstwą interakcji i interpretacji." },
      { type: "paragraph", text: "Manager może zapytać:" },
      { type: "paragraph", text: "Dlaczego EBITDA w Czechach spadła względem forecastu?" },
      { type: "paragraph", text: "System pobiera odpowiednie dane, wykonuje analizę i przedstawia wynik w naturalnym języku." },
      { type: "paragraph", text: "Dobra architektura może więc wyglądać:" },
      { type: "formula", lines: ["źródła → model danych → wspólne definicje → analiza → prezentacja → interpretacja → decyzja"] },
      { type: "paragraph", text: "Excel, BI i LLM nie muszą ze sobą konkurować." },
      { type: "paragraph", text: "Każde narzędzie powinno robić to, do czego nadaje się najlepiej." }
    ]
  },
  {
    number: 9,
    slug: "od-dashboardu-do-decyzji-kpi",
    title: "Od dashboardu do decyzji: dlaczego więcej KPI często pogarsza controlling",
    excerpt: "Więcej KPI nie musi oznaczać lepszego zarządzania. Jak projektować informację od decyzji, przez wskaźnik i próg, do działania.",
    category: "Controlling × AI",
    track: "controlling-ai",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "Można mieć ogromną ilość danych i bardzo mało informacji." },
      { type: "paragraph", text: "Dashboard ma 40 KPI." },
      { type: "paragraph", text: "Raport miesięczny 80 stron." },
      { type: "paragraph", text: "Manager otrzymuje kilkanaście zestawień." },
      { type: "paragraph", text: "A na spotkaniu zarządu pada pytanie:" },
      { type: "paragraph", text: "Co właściwie powinniśmy zrobić?" },
      { type: "paragraph", text: "To sygnał, że controlling zatrzymał się na poziomie raportowania." },
      { type: "heading", text: "Odwróćmy proces" },
      { type: "paragraph", text: "Nie zaczynajmy od:" },
      { type: "paragraph", text: "Jakie dane mamy?" },
      { type: "paragraph", text: "Zacznijmy od:" },
      { type: "callout", text: "Jaką decyzję manager musi podjąć?" },
      { type: "paragraph", text: "Potem:" },
      { type: "paragraph", text: "Jakiej informacji potrzebuje?" },
      { type: "paragraph", text: "Następnie:" },
      { type: "paragraph", text: "Jaki KPI najlepiej ją reprezentuje?" },
      { type: "paragraph", text: "I wreszcie:" },
      { type: "paragraph", text: "Kiedy zmiana wskaźnika powinna wywołać działanie?" },
      { type: "paragraph", text: "Można to zapisać:" },
      { type: "formula", lines: ["Decision → Information → KPI → Threshold → Action"] },
      { type: "heading", text: "Przykład należności" },
      { type: "paragraph", text: "Firma monitoruje 20 wskaźników związanych z należnościami." },
      { type: "paragraph", text: "Zamiast tego zacznijmy od decyzji:" },
      { type: "paragraph", text: "Kiedy ograniczyć sprzedaż kredytową dla klienta?" },
      { type: "paragraph", text: "Potrzebujemy wtedy kilku informacji:" },
      { type: "paragraph", text: "ekspozycji, opóźnienia, historii płatności i znaczenia klienta." },
      { type: "paragraph", text: "20 KPI może zamienić się w cztery informacje." },
      { type: "paragraph", text: "Ale wszystkie prowadzą do konkretnego działania." },
      { type: "heading", text: "AI może pójść jeszcze krok dalej" },
      { type: "paragraph", text: "Klasyczny dashboard pokazuje:" },
      { type: "paragraph", text: "DSO = 52 dni." },
      { type: "paragraph", text: "AI może powiedzieć:" },
      { type: "paragraph", text: "DSO wzrosło o 6 dni, ale 80% pogorszenia wynika z pięciu klientów. Dwóch przekroczyło termin o ponad 30 dni, a łączna ekspozycja wynosi 3,2 mln zł." },
      { type: "paragraph", text: "To już nie tylko wskaźnik." },
      { type: "paragraph", text: "To identyfikacja problemu." },
      { type: "paragraph", text: "A system może jeszcze dodać:" },
      { type: "paragraph", text: "Warto sprawdzić możliwość eskalacji windykacji dla klientów A i B." },
      { type: "callout", text: "Nowoczesny controlling nie powinien pokazywać managerowi wszystkiego." },
      { type: "callout", text: "Powinien filtrować rzeczywistość:" },
      { type: "paragraph", text: "Co jest normalne?" },
      { type: "paragraph", text: "Co się zmieniło?" },
      { type: "paragraph", text: "Co jest materialne?" },
      { type: "paragraph", text: "Co wymaga decyzji?" },
      { type: "paragraph", text: "Najciekawsza rola AI w raportowaniu może więc brzmieć:" },
      { type: "callout", label: "Cel", text: "spośród tysiąca zmian te trzy wymagają dziś Twojej uwagi." }
    ]
  },
  {
    number: 10,
    slug: "roi-z-ai-w-controllingu",
    title: "Jak mierzyć ROI z AI w controllingu?",
    excerpt: "Jak przejść od efektownego PoC do policzalnej wartości: efektywność, jakość, szybkość, decyzje i ostatecznie wynik biznesowy.",
    category: "Controlling × AI",
    track: "controlling-ai",
    readTime: "4 min",
    blocks: [
      { type: "lead", text: "AI łatwo robi efektowne demo." },
      { type: "paragraph", text: "Znacznie trudniej pokazać, że tworzy realną wartość." },
      { type: "paragraph", text: "Model odpowiada na pytania." },
      { type: "paragraph", text: "Generuje komentarz." },
      { type: "paragraph", text: "Prezentacja wygląda nowocześnie." },
      { type: "paragraph", text: "Ale po sześciu miesiącach zarząd może zapytać:" },
      { type: "paragraph", text: "Ile właściwie na tym zyskaliśmy?" },
      { type: "paragraph", text: "Jeżeli nie potrafimy odpowiedzieć, projekt ma problem." },
      { type: "heading", text: "Najpierw baseline" },
      { type: "paragraph", text: "Przed wdrożeniem trzeba wiedzieć, jak proces wygląda dzisiaj." },
      { type: "paragraph", text: "Jeżeli przygotowanie raportu zarządczego wymaga 80 godzin pracy miesięcznie, a po wdrożeniu 35, odzyskaliśmy 45 godzin." },
      { type: "paragraph", text: "To łatwo policzyć." },
      { type: "paragraph", text: "Ale ROI z AI może występować na kilku poziomach." },
      { type: "heading", text: "1. Efektywność" },
      { type: "paragraph", text: "Ile pracy udało się ograniczyć?" },
      { type: "paragraph", text: "Ile procesów manualnych zniknęło?" },
      { type: "heading", text: "2. Jakość" },
      { type: "paragraph", text: "Czy zmniejszyła się liczba błędów?" },
      { type: "paragraph", text: "Czy informacje są bardziej spójne?" },
      { type: "heading", text: "3. Szybkość" },
      { type: "paragraph", text: "Czy zarząd otrzymuje informacje wcześniej?" },
      { type: "paragraph", text: "Czy forecast jest aktualizowany częściej?" },
      { type: "heading", text: "4. Jakość decyzji" },
      { type: "paragraph", text: "Czy problem został wykryty wcześniej?" },
      { type: "paragraph", text: "Czy controller ma więcej czasu na analizę?" },
      { type: "paragraph", text: "Czy manager otrzymuje lepsze scenariusze?" },
      { type: "heading", text: "5. Wynik biznesowy" },
      { type: "paragraph", text: "To najtrudniejszy, ale najważniejszy poziom." },
      { type: "paragraph", text: "Przykładowo:" },
      { type: "paragraph", text: "system wcześniej wykrył pogarszającą się rentowność grupy klientów → zmieniono pricing → marża poprawiła się o X." },
      { type: "paragraph", text: "Albo:" },
      { type: "paragraph", text: "system wskazał wzrost ryzyka należności → organizacja szybciej zareagowała → ograniczono ekspozycję." },
      { type: "paragraph", text: "Tutaj technologia zaczyna wpływać nie tylko na controlling, ale na ekonomię firmy." },
      { type: "heading", text: "Nie każdy PoC powinien być skalowany" },
      { type: "paragraph", text: "Projekt może działać technicznie i nie mieć sensu biznesowego." },
      { type: "paragraph", text: "Jeżeli automatyzacja oszczędza dwie godziny miesięcznie, ale utrzymanie rozwiązania kosztuje kilkadziesiąt tysięcy rocznie, zamiast sukcesu mamy ciekawy eksperyment." },
      { type: "paragraph", text: "Dlatego jeszcze przed prototypem warto ustalić:" },
      { type: "paragraph", text: "Po czym poznamy, że projekt warto rozwijać?" },
      { type: "paragraph", text: "Największy ROI nie musi też oznaczać redukcji etatów." },
      { type: "paragraph", text: "Ten sam zespół może analizować więcej danych, wcześniej wykrywać problemy, częściej aktualizować forecast i spędzać więcej czasu z biznesem." },
      { type: "paragraph", text: "Dlatego końcowe pytanie nie powinno brzmieć tylko:" },
      { type: "callout", text: "Czy dzięki AI controlling jest tańszy?" },
      { type: "paragraph", text: "Lepiej zapytać:" },
      { type: "callout", text: "Czy dzięki AI controlling pomaga firmie podejmować lepsze decyzje i osiągać lepsze wyniki?" },
      { type: "paragraph", text: "To znacznie ambitniejsza miara. I moim zdaniem właściwa." }
    ]
  }
];

export const knowledgeCategories = [
  "Wszystkie",
  "Fundamenty finansów",
  "Płynność i gotówka",
  "Rentowność i sprzedaż",
  "Ludzie i koszty pracy",
  "Cena i podatki"
] as const;

export function getKnowledgeArticle(slug: string) {
  return knowledgeArticles.find((article) => article.slug === slug);
}
